spring:
  data:
    mongodb:
      database: everkeep
      url: ${SPRING_DATA_MONGODB_URL}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    protocol: ${SPRING_MAIL_PROTOCOL}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

security:
  verification:
    expirationTimeSec: 2592000 # 1 month

integration:
  uiUrl: ${INTEGRATION_UI_URL}
